# Generated by Django 5.1.3 on 2024-12-03 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0002_remove_todo_sino_remove_todo_status_remove_todo_task_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='date',
            new_name='Date',
        ),
    ]
