# Generated by Django 5.1.3 on 2024-12-03 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoApp', '0003_rename_date_todo_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='Date',
            new_name='date',
        ),
    ]
